version: "3"
services:
  gobarberdb:
    container_name: gobarberdb
    image: postgres
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
  gobarberdbadmin:
    container_name: gobarberdbadmin
    image: dpage/pgadmin4:4.15
    environment:
      PGADMIN_DEFAULT_EMAIL: gostack@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: docker
    ports:
      - "5050:80"
    depends_on:
      - gobarberdb
